---
version: '3.3'
services:
  zookeeper1:
    image: confluentinc/cp-zookeeper:5.4.3
    hostname: zookeeper1
    ports:
      - '22181:22181'
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 22181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:22888:23888;zookeeper2:32888:33888;zookeeper3:42888:43888
    volumes:
      - ./dockerdata/1.0/zookeeper_1/zk-data:/var/lib/zookeeper/data
      - ./dockerdata/1.0/zookeeper_1/zk-txn-logs:/var/lib/zookeeper/log

  zookeeper2:
    image: confluentinc/cp-zookeeper:5.4.3
    hostname: zookeeper2
    ports:
      - '32181:32181'
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:22888:23888;zookeeper2:32888:33888;zookeeper3:42888:43888
    volumes:
      - ./dockerdata/1.0/zookeeper_2/zk-data:/var/lib/zookeeper/data
      - ./dockerdata/1.0/zookeeper_2/zk-txn-logs:/var/lib/zookeeper/log

  zookeeper3:
    image: confluentinc/cp-zookeeper:5.4.3
    hostname: zookeeper3
    ports:
      - '42181:42181'
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 42181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_SERVERS: zookeeper1:22888:23888;zookeeper2:32888:33888;zookeeper3:42888:43888
    volumes:
      - ./dockerdata/1.0/zookeeper_3/zk-data:/var/lib/zookeeper/data
      - ./dockerdata/1.0/zookeeper_3/zk-txn-logs:/var/lib/zookeeper/log

  kafka1:
    image: confluentinc/cp-kafka:5.4.3
    hostname: kafka1
    expose:
      - "19092"
    ports:
      - '19093:19093'
    links:
     - "zookeeper1"
     - "zookeeper2"
     - "zookeeper3"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:22181,zookeeper2:32181,zookeeper3:42181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:19092,PLAINTEXT_HOST://localhost:19093
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CLEANUP_POLICY: "delete"
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 7200000
    volumes:
      - ./dockerdata/1.0/kafka_1/kakfa-data:/var/lib/kafka/data

  kafka2:
    image: confluentinc/cp-kafka:5.4.3
    hostname: kafka2
    expose:
      - "29092"
    ports:
      - '29093:29093'
    links:
     - "zookeeper1"
     - "zookeeper2"
     - "zookeeper3"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:22181,zookeeper2:32181,zookeeper3:42181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29092,PLAINTEXT_HOST://localhost:29093
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CLEANUP_POLICY: "delete"
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 7200000
    volumes:
      - ./dockerdata/1.0/kafka_2/kakfa-data:/var/lib/kafka/data

  kafka3:
    image: confluentinc/cp-kafka:5.4.3
    hostname: kafka3
    expose:
      - "39092"
    ports:
      - '39093:39093'
    links:
     - "zookeeper1"
     - "zookeeper2"
     - "zookeeper3"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper1:22181,zookeeper2:32181,zookeeper3:42181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:39092,PLAINTEXT_HOST://localhost:39093
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CLEANUP_POLICY: "delete"
      KAFKA_LOG_CLEANER_DELETE_RETENTION_MS: 7200000
    volumes:
      - ./dockerdata/1.0/kafka_3/kakfa-data:/var/lib/kafka/data
